name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        # Removed cache: 'npm' line that was causing the error
    
    - name: Install dependencies
      run: npm install
    
    - name: Run basic checks
      run: |
        echo "✅ Dependencies installed successfully"
        echo "✅ Node.js version: $(node --version)"
        echo "✅ NPM version: $(npm --version)"
    
    - name: Check project structure
      run: |
        test -f package.json && echo "✅ package.json found"
        test -f server.js && echo "✅ server.js found"
        test -d games && echo "✅ games folder found"
        test -d public && echo "✅ public folder found"
        echo "🎮 Retro arcade project structure verified!"
